### ISSUE TITLE
Error in the softwareserial example

### ISSUE THREAD

**Issue by OxMarco** [RBEGamer/HLK-LD2450#2]
The softwareserial example fails to compile for Arduino UNO
```
softwareserial.ino:53: undefined reference to `LD2450::begin(SoftwareSerial&, bool)'
```

**Comment by RBEGamer** [comment]
Hi, sorry for the late answer. currently the SoftwareSerial example isn't working, due to SoftwareSerial library speed baud rate limitations. It's possible to add a #define ENABLE_SOFTWARESERIAL_SUPPORT in the ld2450.h file to enable this feature. I tested several software serial / avr Arduino combinations with no success using software serial. can you specify your hardware platform ?

**Comment by yukiloh** [comment]
I am using ESP8266, it only has 2 Serial, one of them can only be RX(for some reason...)
So I tried to use Softwareserial, but I got an error(I added `#define ENABLE_SOFTWARESERIAL_SUPPORT`):
```
main.cpp.o:(.text.setup+0xc): undefined reference to '_ZN6LD24505beginERN17EspSoftwareSerial9BasicUARTINS0_16GpioCapabilitiesEEEb'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp12e\firmware.elf] Error 1
```
But Hardwareserial works fine on ESP32, looking forward to fixing Softwareserial

**Comment by OxMarco** [comment]
> Hi, sorry for the late answer. currently the SoftwareSerial example isn't working, due to SoftwareSerial library speed baud rate limitations. It's possible to add a #define ENABLE_SOFTWARESERIAL_SUPPORT in the ld2450.h file to enable this feature. I tested several software serial / avr Arduino combinations with no success using software serial. can you specify your hardware platform ?

Arduino UNO rev 3

**Comment by RBEGamer** [comment]
Only RX is completely OK, no sensor configuration takes place via the TX lines, so you can remove the TX line from the sensor to the esp.

**Comment by RBEGamer** [comment]
The Arduino UNO rev 3 and the current Software-Serial library is currently not capable to handle such baud rate speeds, the max baudrate is around 115200 but the sensor requires a mich faster.
I removed the SS option in the current release of this lib until resolved.
