### ISSUE TITLE
result_target.distance is always 0

### ISSUE THREAD

**Issue by Lucian-Nicoara** [RBEGamer/HLK-LD2450#4]
if i try:
const LD2450::RadarTarget result_target = ld2450.getTarget(0);
result_target.distance is awlays 0;

Check /src/LD2450.cpp lines 188 to 193 and add LD2450::radarTargets[targetCounter].distance = target.distance;

**Comment by RBEGamer** [comment]
can you create a pull request to fix this issue ?

**Comment by RBEGamer** [comment]
FIXED, thank you!
